// +build !ignore_autogenerated

/*
Copyright 2018 The Kubepack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	apps "github.com/kubepack/packserver/apis/apps"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Manifest_To_apps_Manifest,
		Convert_apps_Manifest_To_v1alpha1_Manifest,
		Convert_v1alpha1_ManifestList_To_apps_ManifestList,
		Convert_apps_ManifestList_To_v1alpha1_ManifestList,
		Convert_v1alpha1_ManifestSpec_To_apps_ManifestSpec,
		Convert_apps_ManifestSpec_To_v1alpha1_ManifestSpec,
		Convert_v1alpha1_ManifestStatus_To_apps_ManifestStatus,
		Convert_apps_ManifestStatus_To_v1alpha1_ManifestStatus,
		Convert_v1alpha1_Release_To_apps_Release,
		Convert_apps_Release_To_v1alpha1_Release,
		Convert_v1alpha1_ReleaseList_To_apps_ReleaseList,
		Convert_apps_ReleaseList_To_v1alpha1_ReleaseList,
		Convert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec,
		Convert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec,
		Convert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus,
		Convert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus,
		Convert_v1alpha1_User_To_apps_User,
		Convert_apps_User_To_v1alpha1_User,
		Convert_v1alpha1_UserList_To_apps_UserList,
		Convert_apps_UserList_To_v1alpha1_UserList,
	)
}

func autoConvert_v1alpha1_Manifest_To_apps_Manifest(in *Manifest, out *apps.Manifest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ManifestSpec_To_apps_ManifestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ManifestStatus_To_apps_ManifestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Manifest_To_apps_Manifest is an autogenerated conversion function.
func Convert_v1alpha1_Manifest_To_apps_Manifest(in *Manifest, out *apps.Manifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_Manifest_To_apps_Manifest(in, out, s)
}

func autoConvert_apps_Manifest_To_v1alpha1_Manifest(in *apps.Manifest, out *Manifest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_apps_ManifestSpec_To_v1alpha1_ManifestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_apps_ManifestStatus_To_v1alpha1_ManifestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_apps_Manifest_To_v1alpha1_Manifest is an autogenerated conversion function.
func Convert_apps_Manifest_To_v1alpha1_Manifest(in *apps.Manifest, out *Manifest, s conversion.Scope) error {
	return autoConvert_apps_Manifest_To_v1alpha1_Manifest(in, out, s)
}

func autoConvert_v1alpha1_ManifestList_To_apps_ManifestList(in *ManifestList, out *apps.ManifestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]apps.Manifest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ManifestList_To_apps_ManifestList is an autogenerated conversion function.
func Convert_v1alpha1_ManifestList_To_apps_ManifestList(in *ManifestList, out *apps.ManifestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManifestList_To_apps_ManifestList(in, out, s)
}

func autoConvert_apps_ManifestList_To_v1alpha1_ManifestList(in *apps.ManifestList, out *ManifestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Manifest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_apps_ManifestList_To_v1alpha1_ManifestList is an autogenerated conversion function.
func Convert_apps_ManifestList_To_v1alpha1_ManifestList(in *apps.ManifestList, out *ManifestList, s conversion.Scope) error {
	return autoConvert_apps_ManifestList_To_v1alpha1_ManifestList(in, out, s)
}

func autoConvert_v1alpha1_ManifestSpec_To_apps_ManifestSpec(in *ManifestSpec, out *apps.ManifestSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ManifestSpec_To_apps_ManifestSpec is an autogenerated conversion function.
func Convert_v1alpha1_ManifestSpec_To_apps_ManifestSpec(in *ManifestSpec, out *apps.ManifestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManifestSpec_To_apps_ManifestSpec(in, out, s)
}

func autoConvert_apps_ManifestSpec_To_v1alpha1_ManifestSpec(in *apps.ManifestSpec, out *ManifestSpec, s conversion.Scope) error {
	return nil
}

// Convert_apps_ManifestSpec_To_v1alpha1_ManifestSpec is an autogenerated conversion function.
func Convert_apps_ManifestSpec_To_v1alpha1_ManifestSpec(in *apps.ManifestSpec, out *ManifestSpec, s conversion.Scope) error {
	return autoConvert_apps_ManifestSpec_To_v1alpha1_ManifestSpec(in, out, s)
}

func autoConvert_v1alpha1_ManifestStatus_To_apps_ManifestStatus(in *ManifestStatus, out *apps.ManifestStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ManifestStatus_To_apps_ManifestStatus is an autogenerated conversion function.
func Convert_v1alpha1_ManifestStatus_To_apps_ManifestStatus(in *ManifestStatus, out *apps.ManifestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManifestStatus_To_apps_ManifestStatus(in, out, s)
}

func autoConvert_apps_ManifestStatus_To_v1alpha1_ManifestStatus(in *apps.ManifestStatus, out *ManifestStatus, s conversion.Scope) error {
	return nil
}

// Convert_apps_ManifestStatus_To_v1alpha1_ManifestStatus is an autogenerated conversion function.
func Convert_apps_ManifestStatus_To_v1alpha1_ManifestStatus(in *apps.ManifestStatus, out *ManifestStatus, s conversion.Scope) error {
	return autoConvert_apps_ManifestStatus_To_v1alpha1_ManifestStatus(in, out, s)
}

func autoConvert_v1alpha1_Release_To_apps_Release(in *Release, out *apps.Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Release_To_apps_Release is an autogenerated conversion function.
func Convert_v1alpha1_Release_To_apps_Release(in *Release, out *apps.Release, s conversion.Scope) error {
	return autoConvert_v1alpha1_Release_To_apps_Release(in, out, s)
}

func autoConvert_apps_Release_To_v1alpha1_Release(in *apps.Release, out *Release, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_apps_Release_To_v1alpha1_Release is an autogenerated conversion function.
func Convert_apps_Release_To_v1alpha1_Release(in *apps.Release, out *Release, s conversion.Scope) error {
	return autoConvert_apps_Release_To_v1alpha1_Release(in, out, s)
}

func autoConvert_v1alpha1_ReleaseList_To_apps_ReleaseList(in *ReleaseList, out *apps.ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]apps.Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReleaseList_To_apps_ReleaseList is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseList_To_apps_ReleaseList(in *ReleaseList, out *apps.ReleaseList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseList_To_apps_ReleaseList(in, out, s)
}

func autoConvert_apps_ReleaseList_To_v1alpha1_ReleaseList(in *apps.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Release)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_apps_ReleaseList_To_v1alpha1_ReleaseList is an autogenerated conversion function.
func Convert_apps_ReleaseList_To_v1alpha1_ReleaseList(in *apps.ReleaseList, out *ReleaseList, s conversion.Scope) error {
	return autoConvert_apps_ReleaseList_To_v1alpha1_ReleaseList(in, out, s)
}

func autoConvert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec(in *ReleaseSpec, out *apps.ReleaseSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec(in *ReleaseSpec, out *apps.ReleaseSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseSpec_To_apps_ReleaseSpec(in, out, s)
}

func autoConvert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *apps.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return nil
}

// Convert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec is an autogenerated conversion function.
func Convert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec(in *apps.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return autoConvert_apps_ReleaseSpec_To_v1alpha1_ReleaseSpec(in, out, s)
}

func autoConvert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus(in *ReleaseStatus, out *apps.ReleaseStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus(in *ReleaseStatus, out *apps.ReleaseStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseStatus_To_apps_ReleaseStatus(in, out, s)
}

func autoConvert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *apps.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	return nil
}

// Convert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus is an autogenerated conversion function.
func Convert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus(in *apps.ReleaseStatus, out *ReleaseStatus, s conversion.Scope) error {
	return autoConvert_apps_ReleaseStatus_To_v1alpha1_ReleaseStatus(in, out, s)
}

func autoConvert_v1alpha1_User_To_apps_User(in *User, out *apps.User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.DisallowedPacks = *(*[]string)(unsafe.Pointer(&in.DisallowedPacks))
	return nil
}

// Convert_v1alpha1_User_To_apps_User is an autogenerated conversion function.
func Convert_v1alpha1_User_To_apps_User(in *User, out *apps.User, s conversion.Scope) error {
	return autoConvert_v1alpha1_User_To_apps_User(in, out, s)
}

func autoConvert_apps_User_To_v1alpha1_User(in *apps.User, out *User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.DisallowedPacks = *(*[]string)(unsafe.Pointer(&in.DisallowedPacks))
	return nil
}

// Convert_apps_User_To_v1alpha1_User is an autogenerated conversion function.
func Convert_apps_User_To_v1alpha1_User(in *apps.User, out *User, s conversion.Scope) error {
	return autoConvert_apps_User_To_v1alpha1_User(in, out, s)
}

func autoConvert_v1alpha1_UserList_To_apps_UserList(in *UserList, out *apps.UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]apps.User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_UserList_To_apps_UserList is an autogenerated conversion function.
func Convert_v1alpha1_UserList_To_apps_UserList(in *UserList, out *apps.UserList, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserList_To_apps_UserList(in, out, s)
}

func autoConvert_apps_UserList_To_v1alpha1_UserList(in *apps.UserList, out *UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_apps_UserList_To_v1alpha1_UserList is an autogenerated conversion function.
func Convert_apps_UserList_To_v1alpha1_UserList(in *apps.UserList, out *UserList, s conversion.Scope) error {
	return autoConvert_apps_UserList_To_v1alpha1_UserList(in, out, s)
}
