/*
Copyright 2018 The Kubepack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	tamal "github.com/kubepack/packserver/apis/tamal"
	clientset_internalversion "github.com/kubepack/packserver/client/clientset/internalversion"
	internalinterfaces "github.com/kubepack/packserver/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/kubepack/packserver/client/listers/tamal/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PackInformer provides access to a shared informer and lister for
// Packs.
type PackInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.PackLister
}

type packInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPackInformer constructs a new informer for Pack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPackInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPackInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPackInformer constructs a new informer for Pack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPackInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Tamal().Packs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Tamal().Packs(namespace).Watch(options)
			},
		},
		&tamal.Pack{},
		resyncPeriod,
		indexers,
	)
}

func (f *packInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPackInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *packInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tamal.Pack{}, f.defaultInformer)
}

func (f *packInformer) Lister() internalversion.PackLister {
	return internalversion.NewPackLister(f.Informer().GetIndexer())
}
