/*
Copyright 2018 The Kubepack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	tamal_v1alpha1 "github.com/kubepack/packserver/apis/tamal/v1alpha1"
	versioned "github.com/kubepack/packserver/client/clientset/versioned"
	internalinterfaces "github.com/kubepack/packserver/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubepack/packserver/client/listers/tamal/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PackInformer provides access to a shared informer and lister for
// Packs.
type PackInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PackLister
}

type packInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPackInformer constructs a new informer for Pack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPackInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPackInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPackInformer constructs a new informer for Pack type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPackInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TamalV1alpha1().Packs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TamalV1alpha1().Packs(namespace).Watch(options)
			},
		},
		&tamal_v1alpha1.Pack{},
		resyncPeriod,
		indexers,
	)
}

func (f *packInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPackInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *packInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tamal_v1alpha1.Pack{}, f.defaultInformer)
}

func (f *packInformer) Lister() v1alpha1.PackLister {
	return v1alpha1.NewPackLister(f.Informer().GetIndexer())
}
